version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "saturday"

  - package-ecosystem: "npm"
    directory: "/cli"
    schedule:
      interval: "monthly"
      day: "saturday"
