version: 2
updates:
  - package-ecosystem: "npm"
    open-pull-requests-limit: 2
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"

  - package-ecosystem: "npm"
    open-pull-requests-limit: 2
    directory: "/cli"
    schedule:
      interval: "weekly"
      day: "monday"
