packageExtensions:
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: "*"
  styled-components@*:
    dependencies:
      react-is: "*"

yarnPath: .yarn/releases/yarn-sources.cjs
