name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          cache: pnpm
          node-version-file: .tool-versions

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run pnpm lint:eslint
        if: ${{ success() || failure() }}
        run: |
          if ! pnpm lint:eslint; then
            echo ''
            echo ''
            echo 'ℹ️ ℹ️ ℹ️'
            echo 'Try running `pnpm fix:eslint` locally to apply autofixes.'
            echo 'ℹ️ ℹ️ ℹ️'
            exit 1
          fi

      - name: Run pnpm lint:markdownlint
        if: ${{ success() || failure() }}
        run: |
          if ! pnpm lint:markdownlint; then
            echo ''
            echo ''
            echo 'ℹ️ ℹ️ ℹ️'
            echo 'Try running `pnpm fix:markdownlint` locally to apply autofixes.'
            echo 'ℹ️ ℹ️ ℹ️'
            exit 1
          fi

      - name: Run pnpm lint:pnpm-dedupe
        if: ${{ success() || failure() }}
        run: |
          if ! pnpm lint:pnpm-dedupe; then
            echo ''
            echo ''
            echo 'ℹ️ ℹ️ ℹ️'
            echo 'Some dependencies can be deduplicated, which will make pnpm-lock.yaml'
            echo 'lighter and potentially save us from unexplainable bugs.'
            echo 'Please run `pnpm fix:pnpm-dedupe` locally and commit pnpm-lock.yaml.'
            echo 'ℹ️ ℹ️ ℹ️'
            exit 1
          fi

      - name: Run pnpm lint:prettier
        if: ${{ success() || failure() }}
        run: |
          if ! pnpm lint:prettier; then
            echo ''
            echo ''
            echo 'ℹ️ ℹ️ ℹ️'
            echo 'Try running `pnpm fix:prettier` locally to apply autofixes.'
            echo 'ℹ️ ℹ️ ℹ️'
            exit 1
          fi

      - name: Run pnpm lint:tsc
        if: ${{ success() || failure() }}
        run: |
          if ! pnpm lint:tsc; then
            echo ''
            echo ''
            echo 'ℹ️ ℹ️ ℹ️'
            echo 'Please fix the above errors locally for the check to pass.'
            echo 'If you don’t see them, try merging target branch into yours.'
            echo 'ℹ️ ℹ️ ℹ️'
            exit 1
          fi
