name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    environment: release
    if: github.repository == 'kachkaev/njt'
    name: Release
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10

      - name: Setup node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          cache: pnpm
          node-version-file: .tool-versions

      - name: Install dependencies
        run: pnpm install

      - name: Verify CLI build
        run: pnpm --filter njt build

      - name: Verify bundled CLI
        run: node cli/dist/cli.js --help

      - name: Create release pull request or publish to npm
        uses: changesets/action@a45c4d594aa4e2c509dc14a9f2b3b67ba3780d0d # v1.9.0
        with:
          title: Version packages
          version: pnpm changesets:version
          publish: pnpm changesets:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
